// Generates frontend/admin/src/components/admin/providerIcons.ts from official icon sets (simple-icons, LobeHub static SVG).
const fs = require('fs');
const path = require('path');
const si = require('simple-icons');

const LOBE = path.join(__dirname, 'node_modules/@lobehub/icons-static-svg/icons');
const OUT = path.join(__dirname, '../../frontend/admin/src/components/admin/providerIcons.ts');

const lobeInner = (file) => {
  const svg = fs.readFileSync(path.join(LOBE, file), 'utf8');
  return svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>.*?<\/title>/, '');
};
const single = (icon, fill) => `<path d="${icon.path}" fill="${fill || '#' + icon.hex}"/>`;

const icons = {
  gemini: { viewBox: '0 0 24 24', markup: lobeInner('gemini-color.svg'), source: 'LobeHub icons (Gemini, colour)' },
  groq: { viewBox: '0 0 24 24', markup: lobeInner('groq.svg').replace('<path ', '<path fill="#F55036" '), source: 'LobeHub icons (Groq)' },
  elevenlabs: { viewBox: '0 0 24 24', markup: lobeInner('elevenlabs.svg').replace('<path ', '<path fill="#111827" '), source: 'LobeHub icons (ElevenLabs)' },
  deepgram: { viewBox: '0 0 24 24', markup: single(si.siDeepgram), source: 'Simple Icons' },
  whatsapp: { viewBox: '0 0 24 24', markup: single(si.siWhatsapp), source: 'Simple Icons' },
  platform_smtp: { viewBox: '0 0 24 24', markup: single(si.siResend, '#111827'), source: 'Simple Icons (Resend)' },
  razorpay: { viewBox: '0 0 24 24', markup: single(si.siRazorpay), source: 'Simple Icons' },
  stripe: { viewBox: '0 0 24 24', markup: single(si.siStripe), source: 'Simple Icons' },
  // Twilio is not in the icon sets used here. Hand-drawn approximation of its mark (red circle, four dots), NOT the official artwork.
  twilio: {
    viewBox: '0 0 24 24',
    markup: '<circle cx="12" cy="12" r="10" fill="#F22F46"/><circle cx="9" cy="9" r="2.1" fill="#fff"/><circle cx="15" cy="9" r="2.1" fill="#fff"/><circle cx="9" cy="15" r="2.1" fill="#fff"/><circle cx="15" cy="15" r="2.1" fill="#fff"/>',
    source: 'Hand-drawn approximation (not official)',
  },
};

const body = `// GENERATED by scratch/icons/gen_icons.js. Provider brand marks as static SVG markup (vendored, trusted, never user input).
// Official: Gemini, Groq, ElevenLabs (LobeHub icons), Deepgram, WhatsApp, Resend, Razorpay, Stripe (Simple Icons).
// Twilio is a hand-drawn approximation. Exotel and Cartesia have no icon here: ProviderLogo shows a monogram tile for them.
// To use an official file, add the provider id with its viewBox and inner markup below.

export interface ProviderIcon {
  viewBox: string;
  markup: string;
  source: string;
}

export const PROVIDER_ICONS: Record<string, ProviderIcon> = ${JSON.stringify(icons, null, 2)};
`;
fs.writeFileSync(OUT, body, 'utf8');
console.log('written', OUT, Object.keys(icons).join(', '));
